on: push
name: CI

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: lint
        run: npm run lint
